### ISSUE TITLE
kanau-macro: all derives discard generics (type, lifetime, and const)

### ISSUE THREAD

**Issue by haruki-nikaidou** [suitsu31-club/kanau#1]
Every derive in `kanau-macro` builds its impl from `DeriveInput::ident` alone and never reads `DeriveInput::generics`. The emitted code is always `impl kanau::message::MessageX for #name`, so any generic type fails to compile.

## Reproduction

External consumer crate depending on `kanau` with `features = ["message", "serde_json"]`, each probe compiled in isolation:

```rust
#[derive(serde::Serialize, JsonMessageSer)]
pub struct Wrapper<T>(pub T);
// error[E0107]: missing generics for struct `Wrapper`: expected 1 generic argument

#[derive(serde::Serialize, JsonMessageSer)]
pub struct Borrowed<'a> { pub s: &'a str }
// error[E0726]: implicit elided lifetime not allowed here: expected lifetime parameter

#[derive(serde::Serialize, JsonMessageSer)]
pub struct Arr<const N: usize> { pub xs: [u8; N] }
// error[E0107]: missing generics for struct `Arr`: expected 1 generic argument
```

Affects all ten derives (`Bincode`/`Json`/`Rkyv`/`Prost`/`MusliWire` × `De`/`Ser`).

## The fix is not just `split_for_impl()`

`split_for_impl()` is necessary but insufficient — the codec call still has to type-check for every type parameter. Verified by hand-writing exactly what `split_for_impl()` alone would emit:

```
split_for_impl ALONE                             -> error[E0277]: the trait bound `T: serde::Serialize` is not satisfied
split_for_impl + `T: serde::Serialize`           -> clean
split_for_impl + `where Self: serde::Serialize`  -> clean
```

Both bound policies compile, but `where Self: <backend trait>` is preferable:

- it is backend-agnostic at the macro level (no need to replicate each codec's bound-inference rules), and
- it does not over-constrain types carrying `PhantomData` fields or a custom `#[serde(bound = "...")]`, which a blanket `T: Serialize` on every parameter would wrongly reject.

## Suggested change

In each backend:

```rust
let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();
quote! {
    impl #impl_generics ::kanau::message::MessageSer for #name #ty_generics
    #where_clause  // extended with `Self: <backend trait>`
    { ... }
}
```

## Acceptance

- Generic, lifetime-parameterised, and const-generic types all derive cleanly.
- A `trybuild` case covers each so this cannot silently regress. The current in-crate tests only derive on non-generic structs, which is why this was never caught.
